name: 'RushJS Get Changelog'
author: Paul Mowat
description: 'Github action for getting changelog from rush'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  version:
    description: 'The version of the changelog to retrieve'
    required: true
  project-name:
    description: 'The name of the project to retrieve the changelog for'
    required: true
  working-directory:
    description: 'Specify the root directory for the rush configuration'
    required: false
    default: '.'
outputs:
  markdown: # output will be available to future steps
    description: 'Markdown formatted changelog for the specified version and project'
